### ISSUE TITLE
Add a network pytest mark for tests that use the network

### ISSUE THREAD

**Issue by mcepl** [lektor/lektor#982] opened 2022-01-05 16:37 UTC
Sometimes it's useful to have the tests that use the network marked so they can be skipped easily when we know the network is not available.

This is useful for example on SUSE and openSUSE's build servers. When building our packages the network is disabled so we can assure reproducible builds (among other benefits). With this mark, it's easier to skip tests that can not succeed.

[Patch](https://github.com/lektor/lektor/files/7816358/skip-network-tests.patch.txt) suggesting the solution.

[Complete build logs](https://github.com/lektor/lektor/files/7816362/_log.txt) with all packages used and steps taken to reproduce.

**Comment by dairiki** [comment] 2022-01-06 02:03
This seems like a good idea.

I see you have two tests marked as requiring a network connection.

I think that only [test_path_installed_plugin_is_none][1] is failing because of missing internet connectivity. (It tries to install the `lektor-webpack-support` from PyPI.)

The second test you marked, [test_markdown_links][2] appears to be failing for you due to improper encoding of `;` to `%3B` in a `data:` URL.  (At least, I'm pretty sure that semicolon should not be encoded.  See [RFC 2397](https://datatracker.ietf.org/doc/html/rfc2397).)  Anyway, that failure has nothing to do with lack of internet.

From your `_log.txt` (line 3279):
```
[    9s] _____________________________ test_markdown_links ______________________________
[    9s] 
[    9s] env = <lektor.environment.Environment object at 0x7f50ff0be400>
[    9s] pad = <lektor.db.Pad object at 0x7f50fef50670>
[    9s] 
[    9s]     def test_markdown_links(env, pad):
[    9s]         field = make_field(env, "markdown")
[    9s]         source = DummySource()
[    9s]     
[    9s]         def md(s):
[    9s]             rv = field.deserialize_value(s, pad=pad)
[    9s]             assert isinstance(rv, MarkdownDescriptor)
[    9s]             return str(rv.__get__(source)).strip()
[    9s]     
[    9s]         with Context(pad=pad):
[    9s]             assert md("[foo](http://example.com/)") == (
[    9s]                 '<p><a href="http://example.com/">foo</a></p>'
[    9s]             )
[    9s]             assert md("[foo](javascript:foo)") == (
[    9s]                 '<p><a href="javascript:foo">foo</a></p>'
[    9s]             )
[    9s]     
[    9s]             img = (
[    9s]                 "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4"
[    9s]                 "//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="
[    9s]             )
[    9s] >           assert (
[    9s]                 md("![test](data:image/png;base64,%s)" % img)
[    9s]                 == ('<p><img src="data:image/png;base64,%s" alt="test"></p>') % img
[    9s]             )
[    9s] E           assert '<p><img src=...t="test"></p>' == '<p><img src=...t="test"></p>'
[    9s] E             - <p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="test"></p>
[    9s] E             ?                            ^
[    9s] E             + <p><img src="data:image/png%3Bbase64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="test"></p>
[    9s] E             ?                            ^^^
[    9s] 
[    9s] tests/test_types.py:67: AssertionError
```

I think this might be due to your use of mistune 2.0.1.  (Lektor currently pins `mistune<2`.) Perhaps a buglet in mistune v2? I haven't looked closely enough to say for sure.

As a quick test, I just unplugged my ethernet cable and ran the tests. `tests/test_pluginsystem.py::TestPlugin::test_path_installed_plugin_is_none` is the only test that failed.

[1]: https://github.com/lektor/lektor/blob/f90d5f8fbbdc8bb8bc5e6f2a2982c1468d611145/tests/test_pluginsystem.py#L159
[2]: https://github.com/lektor/lektor/blob/f90d5f8fbbdc8bb8bc5e6f2a2982c1468d611145/tests/test_types.py#L46

**Closed as completed** 2022-01-06 08:13 UTC
Labels: enhancement, testing

**Comment by mcepl** [comment] 2022-01-06 08:58
> The second test you marked, [test_markdown_links](https://github.com/lektor/lektor/blob/f90d5f8fbbdc8bb8bc5e6f2a2982c1468d611145/tests/test_types.py#L46) appears to be failing for you due to improper encoding of `;` to `%3B` in a `data:` URL. (At least, I'm pretty sure that semicolon should not be encoded. See [RFC 2397](https://datatracker.ietf.org/doc/html/rfc2397).) Anyway, that failure has nothing to do with lack of internet.

> I think this might be due to your use of mistune 2.0.1. (Lektor currently pins `mistune<2`.) Perhaps a buglet in mistune v2? I haven't looked closely enough to say for sure.

I use https://github.com/lektor/lektor/pull/944 and it seems to work (except of this test apparently). Do you know where the problem is? `field.deserialize_value()` is lektor’s method, isn’t it?

**Comment by dairiki** [comment] 2022-01-06 18:33
> I use #944 and it seems to work (except of this test apparently). Do you know where the problem is? `field.deserialize_value()` is lektor’s method, isn’t it?

@mcepl I believe the problem is with `mistune==2.0.1`.  (The basic issue — that of overly aggressive %-escaping of URLs — exists in `mistune==2.0.0` as well, but due to an oversight where image src URLs were not being escaped at all, I don't think it triggers this particular test failure in our test suite.)

I've just filed PR lepture/mistune#295 which, I think, fixes the issue.

**Comment by mcepl** [comment] 2022-01-06 21:46
> I've just filed PR [lepture/mistune#295](https://github.com/lepture/mistune/pull/295) which, I think, fixes the issue.

Yes, that fixes it. Thank you.
