### ISSUE TITLE
Include models.ini system field in Lektor CMS

### ISSUE THREAD

**Issue by alan-cugler** [lektor/lektor#543] opened 2018-05-22 15:52 UTC
There should be a system "Models" field in the CMS.

When creating websites I find myself going through refactoring and slowly adding additional features and pages. In my refactoring with Lektor sites, I often replace a single template/model pair with generic templates and nested model.ini and flowblock.ini files to make it more reusable code for the future. 
In the CMS I can make that quick change with templates but not models. 

If we are going to have one available [template field], then the partner files [models field] should also be available to be written in from the CMS.

**Comment by nixjdm** [comment] 2018-05-22 21:15
You can set a model during page creation, so why not change it after it's created?

Implementation issues, for one. Changing models will change all the other fields and saved content for the page. That could be fine, but it is definitely changing more than just **that field** - it'll change the whole admin page and all of that page's data. It should be prompted with a user verification probably, at least if other saved data will change, because it will generally all get deleted.

I'm fine with this, but it definitely has a UX element, unlike changing other existing field. There's something to be said for not having this as well. Perhaps having it, but allowing it to be disabled system-wide in the project file. It's maybe too powerful for a content generator, but might be loved by a dev.

**Comment by nixjdm** [comment] 2018-05-23 17:59
Duplicate of #98

**Closed as completed by nixjdm** 2018-05-23 17:59 UTC
Labels: duplicate, enhancement
