### ISSUE TITLE
Backwards incompatibility in v3.3.2 alternative handling

### ISSUE THREAD

**Issue by freakboy3742** [lektor/lektor#1026] opened 2022-04-06 01:58 UTC
I have [a Lektor site](https://github.com/beeware/beeware.github.io) that deploys fine on Lector 3.3.1; upgrading to 3.3.2 causes multiple failures due to what appears to be an issue with default alternative lookup.

Every page on the site has a `contents.lr`, and `en` is set as the primary language. Partial translations for the site exist in many languages (ar, es, pt, zh, fr, it, pl). However, whenever a translation for a specific language isn't present, it looks for `contents+en.lr` - a file that doesn't exist - and the build fails as a result.

Build Log excerpt:
```
2022-04-06T01:44:17.2474088Z Started build
2022-04-06T01:44:17.2640283Z U ar_AR/index.html
2022-04-06T01:44:17.5287436Z U cs_CZ/index.html
2022-04-06T01:44:17.5820897Z   E cs_CZ/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/contents+en.lr')
2022-04-06T01:44:17.5924754Z U da_DK/index.html
2022-04-06T01:44:17.5983828Z   E da_DK/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/contents+en.lr')
2022-04-06T01:44:17.6085304Z U de_DE/index.html
2022-04-06T01:44:17.7004800Z U index.html
2022-04-06T01:44:17.7845988Z U es/index.html
2022-04-06T01:44:17.8958702Z U fr_FR/index.html
2022-04-06T01:44:17.9884367Z U it_IT/index.html
2022-04-06T01:44:17.9939498Z   E it_IT/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/contents+en.lr')
2022-04-06T01:44:18.0039511Z U ko_KR/index.html
2022-04-06T01:44:18.0093995Z   E ko_KR/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/contents+en.lr')
2022-04-06T01:44:18.0193713Z U pl_PL/index.html
2022-04-06T01:44:18.1121850Z U pt_BR/index.html
2022-04-06T01:44:18.1980698Z U tr_TR/index.html
2022-04-06T01:44:18.2898397Z U zh_TW/index.html
2022-04-06T01:44:18.4029289Z U ar_AR/b/index.html
2022-04-06T01:44:18.4506113Z U ar_AR/batavia/index.html
2022-04-06T01:44:18.4663084Z   E ar_AR/batavia/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/batavia/contents+en.lr')
2022-04-06T01:44:18.4701624Z U ar_AR/cricket/index.html
2022-04-06T01:44:18.4838880Z   E ar_AR/cricket/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/cricket/contents+en.lr')
2022-04-06T01:44:18.4877632Z U ar_AR/colosseum/index.html
2022-04-06T01:44:18.5103121Z   E ar_AR/colosseum/index.html (FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/beeware.github.io/beeware.github.io/content/colosseum/contents+en.lr')
2022-04-06T01:44:18.5141530Z U ar_AR/signup/index.html
...
```
Full log can be found in the CI builds for [this pull request](https://github.com/beeware/beeware.github.io/pull/472).

As best as I can work out, the bug is related to https://github.com/lektor/lektor/pull/958 - however, the commentary on that and related tickets doesn't suggest there is any possible backwards incompatibility or migration required (in fact, the commentary on https://github.com/lektor/lektor/issues/965 seems to specifically dismiss the possibility of backwards incompatibilities).

**Comment by dairiki** [comment] 2022-04-06 03:58
Running the admin server and viewing http://localhost:5000/cs_CZ/ yields:
```
Build Failure :'(
Building of the artifact “cs_CZ/index.html” failed. This is what we know about the problem:

Traceback (most recent call last):
[... some stuff elided...]
  File "/home/dairiki/git/web/lektor-packages/lektor/beeware/templates/home.html", line 15, in top-level template code
    {% set t_ad_hoc_sponsor = transbag('translate', this.alt, 'ad_hoc_sponsor') %}
  File "/home/dairiki/git/web/lektor-packages/lektor/beeware/templates/layout.html", line 105, in top-level template code
    {%- set content_value = urlencode_limit(site.get(this.path).contents.as_text(), limit=5000) -%}
  File "/home/dairiki/git/web/lektor-packages/lektor/lektor/filecontents.py", line 51, in as_text
    with self.open() as f:
  File "/home/dairiki/git/web/lektor-packages/lektor/lektor/filecontents.py", line 66, in open
    return codecs.open(self.filename, encoding=encoding or "utf-8")
  File "/usr/lib/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dairiki/git/web/lektor-packages/lektor/beeware/content/contents+en.lr'

```
The error is exercised by calling `Page.contents` for pages for which (as you say) there is a fallback `contents.lr` but no _primary alt_-specific `contents+en.lr`.

This is  caused by a change in the default value for `alt` in `Pad.get` in (as you say) #958, which results in `site.get("/").source_filename` returning the path to the `contents+en.lr` rather than `contents.lr`.



In `Lektor<=3.3.1`, where `alt` defaults to the constant `PRIMARY_ALT` (equal to the string `"_primary"`), `site.get(path).contents` is always return the content of the fallback file, `contents.lr`.

Lektor 3.3.2 changes `site.get` to default `alt` to the _primary alt_ configured in the `.lektorproject` file — in this case `en`, which is why `site.get(path).contents` is looking for `contents+en.lr`.

## Workaround

I think (untested) that you can restore the previous behavior (in a backward-compatible way) by explicitly specifying `alt="_primary"`: e.g. `site.get(path, alt="_primary").contents`.

## Quandry

When alts are enabled, every page has (potentially) two source filenames: the alt-specific one (`contents+xx.lr`) and the fallback (`contents.lr`).  One or both may actually exist.  If both exist, the data from the alt-specific file is overlayed on the fallback data — the alt-specific data is used for fields that are defined in the alt-specific file, but the fallback data is used for fields that are not.

So, for the sake of dependency tracking, `Page.source_filename` is pretty useless.  The dependency tracking must always consider both (potential) source files, rebuilding the page if either one changes (or is created.)

Also, in light of this `Page.contents` is not always well-defined.  If both alt-specific and the fallback files exist which contents are wanted?  I'm not sure how best to fix this.  I guess if only one of the the two files exists, `Page.contents` could return whichever one that is.

Note that `Page.contents` is not used at all by Lektor itself.  I had been thinking of deprecating it.

In any case, what if both source files (alt-specific and fallback) exist?  What should `Page.contents` return in that case?

**Comment by freakboy3742** [comment] 2022-04-06 04:25
Thanks - adding `alt='_primary'`  to the various calls to `site.get()` looks like it's done the job as a workaround. 

As for fallback strategy; my suggestion would be that "return the most specific" would be the best approach - so `en` is declared as primary, it would return `contents+en.lr`, and then fall back to `contents.lr` if it wasn't available. Having both files present is definitely an edge case; but I'd argue that if `site.get()` is explicit by preference, it's hard to argue that the answer returned is *wrong*, and in the more likely case that only one file is present, both approaches to file naming will work.

As for Page.contents... I can't comment on that one, if only because it's not a feature I use.

**Comment by dairiki** [comment] 2022-04-06 23:55
> As for Page.contents... I can't comment on that one, if only because it's not a feature I use.

Sure you do.  [Here][1] and [here][2].  That's what caused this issue.
`site.get(path)` (`Pad.get(path)`) returns a `Page`, so `site.get(path).contents` is calling the getter for the `Page.contents` property.

[2]: https://github.com/beeware/beeware.github.io/blob/7a1507644f7451f04ea031ce9348c7728617771d/packages/lektor_beeware_plugin/lektor_beeware_plugin.py#L149
[1]: https://github.com/beeware/beeware.github.io/blob/7a1507644f7451f04ea031ce9348c7728617771d/templates/layout.html#L105

FWIW, I think those are the only two instances of `site.get` where you need to add the `alt='_primary'` workaround.   The other cases, where you pass the return value of `site.get` into the `url` filter should more properly omit the `alt` parameter, so as to get the URL to the _primary alt_ version (in your case `"en"`) of the desired record.  (In practice, for getting the default URL probably either no `alt` or `alt='_primary'` will work.)

> Having both files present is definitely an edge case.

Maybe on the Beeware site source it is, but I don't think it is fair to call having both contents files an edge case in general.

If one uses the Lektor admin web UI to construct content for a non-primary alt, generally the alt-specific contents file will only contain those fields which have been specifically edited in the admin UI.  The values for the rest of the fields will still come from the fallback `contents.lr` file.

(Certainly, for most system fields, e.g. `_model`, `_slug`, etc., it generally does not make sense to have the value of the field vary with alt. Because of this, it's generally safer to only define these fields once in the fallback `contents.lr`.)

**Comment by relikd** [comment] 2022-04-07 12:43
> If one uses the Lektor admin web UI to construct content for a non-primary alt, generally the alt-specific contents file will only contain those fields which have been specifically edited in the admin UI. The values for the rest of the fields will still come from the fallback `contents.lr` file.

Came to say the same thing. Adding myself here as an "edge case" 😄 (btw. I am very glad that Lektor *is* using this layered view on source files. Back in 3.2.0 (or earlier) it duplicated all the fields from the fallback. I am happy that this is not the case anymore. Should this close #711?).

Lektor *could* merge the two layers into one before returning `.contents` but then again, as you said, it is not used by Lektor and could be deprecated (I dont use it myself) ... in line with the slogan "and lead us not into temptation".

And for `source_filename`, how about returning the list of sources `source_filenames`?

**Comment by dairiki** [comment] 2022-04-07 22:49
> Lektor _could_ merge the two layers into one before returning `.contents` but then again, as you said, it is not used by Lektor and could be deprecated (I dont use it myself) ... in line with the slogan "and lead us not into temptation".

I guess that would be a fix. It's slightly involved since `Page.contents` returns a `FileContents` instance which has a bunch of methods and properties we'd have to support in order to be backwards compatible.  And it's still not fully backwards compatible (though I think it is in the Beeware case, where all of there overlay files include a full copy of all the fallback fields.) What if some really only wanted the data from the overlay file (rather than the merged contents)?

(We could do that to fix the issue _and_ deprecate it.)

> And for `source_filename`, how about returning the list of sources `source_filenames`?

That already exists in the `iter_source_filenames` method. :-)

**Comment by dairiki** [comment] 2023-03-08 23:19
I don't think this is fixable in a consistent manner (when *alts* are in use.)  Note that for getting at the filenames of the `.lr` files which can comprise the data for a page, `.iter_source_filenames()` is available.

For now, I'm closing this as "wont-fix", and marking `Record.contents` as deprecated.  See #1114.

**Closed as completed by dairiki** 2023-03-08 23:19 UTC
Labels: bug, wontfix
