### ISSUE TITLE
Change .lr to .md is possible?

### ISSUE THREAD

**Issue by ppKrauss** [lektor/lektor#439] opened 2017-09-08 10:38 UTC
We are using `*.lr`  extension that is ugly to read or edit online ([example](https://github.com/frictionlessdata/specs/blob/master/content/contents.lr)). It is possible to change extension (to traditional `*.md`)  without impact in the project?

**Comment by wgwz** [comment] 2017-09-08 12:07
The thing is that they aren't quite markdown files and sometimes they might actually be restructured text.

**Comment by ppKrauss** [comment] 2017-09-08 12:20
An "include *.md" at `file.lr` can be simple and will separate the "pure markdown" from its templates or formating instructions. May be a strategy like [transclusion at Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Transclusion#How_transclusion_works).

...The point is that `REAME.md` files are so commom, and we need "dual function": navigate in Github/Gitlab/etc. and produce a site. It is not only a source  to produce HTML.

PS: for some contexts,  we don't matter about "quite markdown" is only an issue for visualize/edit friendility.

**Comment by wgwz** [comment] 2017-09-08 12:33
I don't think it makes sense to make the change because using restructured text as a format is supported.

**Comment by wgwz** [comment] 2017-09-08 12:40
I've been wanting an include functionality myself! I think there may be a plugin

**Comment by ppKrauss** [comment] 2017-09-08 12:50
Let's add an `include` directive (!), accepting *relative paths*,  as [pointed here](https://github.com/mkdocs/mkdocs/issues/1279).

**Comment by nixjdm** [comment] 2017-09-08 15:21
I'm trying to understand this. So the issue is, that on GitHub, the markdown fields in contents files don't render as markdown but only as text, and that makes it hard to produce a README-like contents file that you can see as rendered markdown on GitHub. Is that right? How big of a need is this?

And your thinking was, if we change just the extension of the contents file, we effectively trick GitHub into rendering it as markdown (it isn't, but parts of it may be markdown). This may work well enough some of the time, but it's not a very elegant solution I think. Files like [this](https://github.com/lektor/lektor-website/blob/master/content/blog/hello-lektor/contents.lr) would be rendered quite oddly.

Why not view and edit the files through Lektor's CMS? That would have the benefit of actually rendering the markdown within the context of the whole site too, which I would think would be a more useful view.

We could possibly add some sort of include feature, but I'd want more clarity on what is desired and a clear use case first. Perhaps it could build off of attachments or databags? We already have those, and flowblocks, so this would have to be some additional needed functionality.

**Comment by ppKrauss** [comment] 2017-09-08 16:58
Hi @nixjdm 

> I'm trying to understand this. So the issue is, that on GitHub (...). Is that right? How big of a need is this?

The use of `README` files in *git* documentation, and the use  of  "pure markdown"  (`*.md`) are [*de facto* standards](https://en.wikipedia.org/wiki/De_facto_standard), so there are thousands of potential users and intersting public. 

> And your thinking was, (...)  effectively trick GitHub into rendering it as markdown (...) but it's not a very elegant solution I think. Files like this would be rendered quite oddly.

Yes, let's think first in an elegant solution. Thinking in typical demands:

1. When the `file.md` **is good enought**, not need any extra-formating or local directives: it is important to set it into the sitemap, the CMS must  use the `file.md` as legitimate content, processing it as `*.lr` file. 

2. When the `file.md` **is incomplete**: need eg. extra-formating. In this case another `content_hub.lr` file  need to include the `file.md`, and, of course, the sitemap must ignore it and use only  `content_hub.lr` .

3. When the `file.md` is only a **snippet**, that will be reused in many  `content.lr` files. In this case the role of the *include* directive is like a [*transclusion*](https://en.wikipedia.org/wiki/Wikipedia:Transclusion#How_transclusion_works).

> Why not view and edit the files through Lektor's CMS? (...)

I can, but it is not only I, a programmer, it is all Github visitors, all Gitlab visitors, etc... all the world. And some people that need to preserve the standard and universal *git* interface, using Atom or any other markdown editor.

> We could possibly add some sort of include feature, 

!!!!

> but I'd want more clarity on what is desired and a clear use case first. 

Explaining above, but please ask details if you need. .. 

> Perhaps it could build off of attachments or databags? We already have those, and flowblocks, so this would have to be some additional needed functionality.

Hum... It is only a `*.lr`  file that can be used also as `*.md`  file...To say that Lektor is a  "polyglot" CMS ;-)
 
PS: for attachments my  dream is to include (or transclude)  CSV files, rendering it as a table. There are some good  renders as [frictionlessData tools](http://frictionlessdata.io/tools/#tools-and-integrations), se for example [this CSV](https://github.com/datasets-br/state-codes/blob/master/data/br-state-codes.csv) rendered [here](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatasets-br%2Fstate-codes%2Fmaster%2Fdatapackage.json)

**Comment by wgwz** [comment] 2017-09-08 21:43
I worry that the top few lines of a .lr file is not markdown. So to call that markdown is confusing. But I think an include directive, inspired by and using jinja, in a body field could be interesting and very useful: 

    {{ include "my_content.md" }}

**Comment by runfalk** [comment] 2017-09-12 09:45
@wgwz: I think you could implement this as a plugin with a custom text widget and a new type named `external-markdown` or similar.

**Comment by nixjdm** [comment] 2018-05-18 18:36
I'm closing this issue as explained in its very similar issue here https://github.com/lektor/lektor/issues/532#issuecomment-390294813. For ongoing related work, see #477 and #541

**Closed as completed by nixjdm** 2018-05-18 18:36 UTC
