### ISSUE TITLE
Some tweaks to make lektor easier on non-techies? (code signing, cc dep, binary caching)

### ISSUE THREAD

**Issue by sherbondy** [lektor/lektor#96] opened 2016-01-13 02:05 UTC
Hey there,

I tried Lektor out on my non-techie mother, and a few issues came up:
1. The Lektor desktop app is not currently code signed. This confused the heck out of my mom, since she did not know how to right click, let alone turn off Gatekeeper. I guess I could do this myself for each release, assuming building the dmg is as simple as running [https://www.npmjs.com/package/electron-builder](electron-builder). 
   Are there any unexpected hurdles in packaging the app binary that I should be aware of?
   Are you philosophically opposed to code-signing for some compatibility reason or frustration with Apple's certificate process?
2. Lektor seemingly required running `cc` to install some of the python packages, although I have yet to track down which packages specifically. I may be entirely mistaken, as the site in question also depended in `lektor-s3`, in which case I'll forward my concern to the plugin's author. Maybe it'd be nice as a community to prefer or at least specify which packages are "non-techie" friendly to install  (i.e. do not require having developer command line tools)?
3. Any chance the lektor desktop app could bundle all of its python dependencies somewhere with the binary itself? The initial install process was painful to council my mother through because she has an older mac with a slow HDD and a poor internet connection. I could try and devise some nice setup for this. I think it falls in line with the ongoing consideration of how Lektor's pip cache should work. It would make the first-install experience that much more delightful.

Thanks again for all of your work, it is empowering my mom to edit [her own site](http://www.maureensherbondy.com/) without being beholden to a private cms that could be shuttered any day or such monstrosities as wordpress.

Cheers,
Ethan

**Comment by sherbondy** [comment] 2016-01-13 03:30
Just realized that you have to pay Apple for a developer license to get a code signing certificate. Pretty disgusting.

**Comment by mitsuhiko** [comment] 2016-01-13 11:37
> The Lektor desktop app is not currently code signed

That's … odd. Because I just checked and it is:

```
$ codesign -dv Lektor.app
Executable=/Volumes/Lektor/Lektor.app/Contents/MacOS/Electron
Identifier=org.pocoo.lektor
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=200 flags=0x0(none) hashes=3+3 location=embedded
Signature size=8562
Timestamp=27 Dec 2015 14:25:09
Info.plist entries=18
TeamIdentifier=ZRL6J4P42H
Sealed Resources version=2 rules=12 files=108
Internal requirements count=1 size=176
```

Can you clarify what the exact problem is that was encountered with the signature?

> Lektor seemingly required running cc to install some of the python packages, although I have yet to track down which packages specifically

That's definitely not the case for the OS X binary. Please provide some information about what needed CC in your case.

> Any chance the lektor desktop app could bundle all of its python dependencies somewhere with the binary itself?

It is? Can you clarify what required downloading Python packages?

**Comment by nixjdm** [comment] 2017-08-10 21:10
I'm going to close this issue. Perhaps it was valid a year and a half ago, but that even seems unlikely, and we never got confirmation from the OP, or reproduced the problems. The current installer comes with it's dependencies packaged, and is signed. If we find something like that again, we'll make a new ticket for it.

**Closed as completed by nixjdm** 2017-08-10 21:10 UTC
Labels: nmi
