### ISSUE TITLE
Field Order Sometimes Wrong

### ISSUE THREAD

**Issue by mitsuhiko** [lektor/lektor#41] opened 2015-12-25 21:20 UTC
The fields when added to a page sometimes seem to be in correct.

**Comment by nixjdm** [comment] 2017-07-08 23:23
Do you mean the order of the fields in admin? I think I need a little more detail on this if it's still an issue. They've been reliable for the things I've done, but I might not have done what caused this for you, or didn't notice it.

**Comment by nixjdm** [comment] 2017-09-22 18:50
I'm marking this as on-hold pending the outcome of #457.

**Comment by nixjdm** [comment] 2018-05-23 17:30
Since we've had further discussion on #457 / #458, I'm removing the on-hold label.

**Comment by yagebu** [comment] 2020-12-19 13:04
This still lacks a reproduction is almost certainly fixed now (this probably happened when incorrect keys where used in React, which shouldn't be the case for the fields now)

**Closed as completed by yagebu** 2020-12-19 13:04 UTC
Labels: bug, help-wanted, beginner-friendly, need-to-reproduce
