### ISSUE TITLE
Don't trigger rebuild on certain file changes

### ISSUE THREAD

**Issue by barryrowlingson** [lektor/lektor#666] opened 2019-07-17 14:24 UTC
At the moment I have a folder that is a git project with lektor and I'm running `lektor server`. It seems that any change in the file system triggers a rebuild.

This means if I do and git operation, like `git commit`, I get a rebuild. Even `git status`. That makes `lektor server` outputs its messages and messes up my next command line, sometimes when I've started typing it (if I'm quick enough) as here where my `find` command gets massacred:

```
$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
$ finStarted build
Finished build in 0.03 sec
Started prune
Finished prune in 0.00 sec
d . -name
```

I could run the server in another terminal, or I could send its output to /dev/null, but if I could tell it to ignore changes in .git then that would be fine.

**Comment by nixjdm** [comment] 2019-07-17 18:39
Duplicate of #550 

This is indeed annoying. FWIW before a fix is made, I always work with multiple terminal tabs, one dedicated to the `lektor server` command. That doesn't prevent the rebuilding, but will avoid your commands being interrupted.

**Closed as completed by nixjdm** 2019-07-17 18:39 UTC
