### ISSUE TITLE
assets folder -> cannot use lektor functions like thumbnail on the asset images

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#487] opened 2017-12-13 13:53 UTC
assets folder -> cannot use lektor functions like thumbnail on the asset images

asset root seems to return a directory instead of a query object, therefore all lektor functions for it like thumbnail do not work. Thus typically, one has to add all asset images in a content folder. So imho:

either make that clear in the documentation, e.g. all images need to go into a content folder, or fix the issue

**Comment by nixjdm** [comment] 2017-12-13 15:59
Duplicate of #484. I copied your comment over there.

**Closed as completed by nixjdm** 2017-12-13 15:59 UTC
Labels: duplicate
