### ISSUE TITLE
Publishing to github pages using https

### ISSUE THREAD

**Issue by Jeroendevr** [lektor/lektor#530] opened 2018-05-02 10:02 UTC
When using the builtin publish  function to publish to github pages. I recieve the following error:
```
Error on request:
Traceback (most recent call last):
  File "c:\users\*\appdata\local\lektor-cli\lib\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "c:\users\*\appdata\local\lektor-cli\lib\lib\site-packages\werkzeug\serving.py", line 261, in execute
    write(data)
  File "c:\users\*\appdata\local\lektor-cli\lib\lib\site-packages\werkzeug\serving.py", line 241, in write
    assert isinstance(data, bytes), 'applications must write bytes'
AssertionError: applications must write bytes
```
![github issue 1jpg](https://user-images.githubusercontent.com/9282470/39517510-4a9d6872-4e00-11e8-98ee-dedbd37e4968.JPG)

In the .letktorproject file I have added the following settings. Did I described the target on a wrong way?

```
[servers.github]
name = GitHub
target = ghpages+https://jeroendevr:password@/jeroendevr.github.io
enabled = yes
default = yes
```

Using windows 10

**Comment by nixjdm** [comment] 2018-05-02 20:06
I don't think this error is your fault, but that there must be a bug in the deploy via admin. I'm pretty sure this is a duplicate of #508, so I will make a note of this there and close this. Thanks for duplicating this and letting us know :/

**Closed as completed** 2018-05-02 20:07 UTC
Labels: duplicate

**Comment by nixjdm** [comment] 2018-05-02 20:09
@Jeroendevr AFIAK you should still be able to do a deploy from the command prompt. If you can't, please let us know.
