### ISSUE TITLE
tweaks to web site to improve ubuntu installation instructions

### ISSUE THREAD

**Issue by androclus** [lektor/lektor#239] opened 2016-07-05 23:44 UTC
**Problems with web site installation instructions:**

1) at the getlektor [Downloads](https://www.getlektor.com/downloads/) page - under the Mac/Linux section:

under Ubuntu, the instruction to 

`curl -sf https://www.getlektor.com/install.sh | sh`

 will not work out of the box. not only imagemagick, but also libssl-dev and python-dev (and perhaps other) packages are all needed. else one gets messages like:

> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
>     build/temp.linux-x86_64-2.7/_openssl.c:429:30: fatal error: openssl/opensslv.h: No such file or directory
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

2) that same page/section indicates that one can go to the [Installation](https://www.getlektor.com/docs/installation/) page for more info on dependences.  but there are 3 problems with that.

a) the installation page seems to give info only for command-line (not desktop app) installation (leaving the visitor to wonder whether the dependencies are the same for both types of install) and

b) that installation page only lists imagemagick (not also libssl-dev and python-dev), and

c) for absolute ubuntu newbies, the actual command for installing imagemagick dependency is missing

**Solution:**

probably the pages should be re-worked.

but for a short-term / easy solution, the following could just be added to both of the above-mentioned web pages:

debian/ubuntu users should do the following before running the install.sh script:

   `sudo apt-get install python-dev libssl-dev imagemagick`

thanks.

**Comment by go-bears** [comment] 2016-07-06 07:23
Hi @androclus

ran into the same problems and made some tweaks to the website. See
https://github.com/lektor/lektor-website/pull/104

The changes passed travis, and I'm hoping the changes will get merged soon.

**Comment by go-bears** [comment] 2016-07-12 22:39
I think this issue can be closed now?  

The pull request that the issue is related to was merged.
https://github.com/lektor/lektor-website/pull/104

**Comment by mitsuhiko** [comment] 2016-07-13 05:44
Indeed. Closing this.

**Closed as completed by mitsuhiko** 2016-07-13 05:44 UTC
