### ISSUE TITLE
Add black/isort to the CI and codebase

### ISSUE THREAD

**Issue by skorokithakis** [lektor/lektor#693] opened 2019-10-03 20:10 UTC
What does everyone think about adding pre-commit with black/isort/flake8 to the codebase? It would make everything look more consistent and would enforce the style at the CI level. flake8 would also get rid of some common bugs.

**Comment by davidism** [comment] 2019-10-03 20:15
I did this relatively recently for the Pallets projects and am definitely happy with the results. I went with [reorder-python-imports][1] instead of isort because it followed the same "no configuration" policy as black. You can check out Werkzeugs's [pre-commit config][2] and [flake8 config][3] if you'd like a starting point.

[1]: https://github.com/asottile/reorder_python_imports
[2]: https://github.com/pallets/werkzeug/blob/e7ba08f209477cb453f15113f9a4d527a6e81bfe/.pre-commit-config.yaml
[3]: https://github.com/pallets/werkzeug/blob/e7ba08f209477cb453f15113f9a4d527a6e81bfe/setup.cfg#L30-L54

**Comment by skorokithakis** [comment] 2019-10-03 20:17
Thanks for that, I've been looking for a project that is compatible with black and is opinionated. I will look into it, but do you know if `reorder-python-imports` can recognize first/third party imports without looking at the env? This is the biggest problem I've had with `isort` in `pre-commit`, although @asottile's `seed-isort-config` kind of mitigates it.

**Comment by davidism** [comment] 2019-10-03 20:20
I haven't had to do anything to get it to split into built-in / third-party / local groups.

**Comment by skorokithakis** [comment] 2019-10-03 20:20
Fantastic, thank you.

**Comment by asottile** [comment] 2019-10-03 20:30
it can yes, I wrote both reorder-python-imports and seed-isort-config (they use the same machinery to determine the third-partied-ness of modules)

**Comment by skorokithakis** [comment] 2019-10-03 20:32
This is great, @asottile, thank you. I'm going to switch everything to `reorder-python-imports`, since it looks like it solves a lot of my isort frustrations.

**Comment by asottile** [comment] 2019-10-03 20:38
:tada: I also wrote pre-commit and maintain flake8 if you need help there too <3

**Comment by skorokithakis** [comment] 2019-10-03 20:40
Did you? Damn, you wrote pretty much my entire linting stack, props. Would you like to join [Code Shelter](https://www.codeshelter.co/) as a maintainer, by any chance?

**Comment by nixjdm** [comment] 2019-10-03 20:40
I'm definitely want to blacken Lektor. I use it in several other projects and love it. Thank you @davidism for your input too. `reorder-python-imports` is something I could use more of in my life.

A drawback of `black`, so it's stated, is making it more difficult to get use out of `git blame`. I think this project is small enough and has enough people involved that can grok most of it, that I don't think that should stop us.

I do want to hold off on this a little though and wait for post 3.2 - which I want to cut soon. I'd rather these large diffs come right after a release, instead of before one.

**Comment by asottile** [comment] 2019-10-03 20:42
> Did you? Damn, you wrote pretty much my entire linting stack, props. Would you like to join [Code Shelter](https://www.codeshelter.co/) as a maintainer, by any chance?

hehe I think I have too much on my plate but thank you for the offer!

**Comment by skorokithakis** [comment] 2019-10-03 20:43
Eh it's on an at-will basis, there's no pressure or anything. Let me know if you change your mind!

**Comment by skorokithakis** [comment] 2019-10-03 20:56
@nixjdm sorry, I just saw your comment. Well, the PR is here, it shouldn't be too hard to just merge after the release (as long as there aren't too many flake8-breaking problems introduced). I have to say, it does look much better after blackifying it.

**Comment by nixjdm** [comment] 2019-10-03 20:59
Np @skorokithakis. I appreciate the enthusiasm, and it does look nice. We'll get it. October should give me some breathing room, so I can cut 3.2 this month almost certainly.

**Comment by skorokithakis** [comment] 2019-10-03 21:01
Hey, wait until I want to add mypy to the list :P

**Comment by runfalk** [comment] 2019-10-04 07:57
I'm also in favor of adding black.

> A drawback of `black`, so it's stated, is making it more difficult to get use out of `git blame`. I think this project is small enough and has enough people involved that can grok most of it, that I don't think that should stop us.

Łukasz Langa (the creator of black) suggests using [git-hyper-blame](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html) as a workaround. That way you can exclude the breaking commit and "see through it". When we have merged #696 we can add that commit to the README and explain how to use it with hyper-blame?

**Comment by hannylicious** [comment] 2019-10-24 01:26
I'm also in favor of Black - I think it's fantastic. We use it where I work.

**Comment by xlotlu** [comment] 2020-10-22 03:52
Since this has been revived, I will express my dissent once more towards the barbaric practice that is black. I will leave the discussion on the technical merits of the implementation to #823, and discuss this here from a philosophical and practical standpoint.

This is an argument that I had brought to the dev team's attention previously, so I'll try to reiterate in a more structured and, well, more polite manner:

To some programmers, code is poetry. Every variable name, function call, newline, every comment, every alignment here and there, every custom indentation, all made to express meaning. They are purposeful, and useful, especially in a language like Python where one's brain is wired to find meaning in whitespace.

Then comes the big hammer that is black and ruins all that.

The problem is not only philosophical, "ouch you ruined my poetry": it's practical. Along with the loss of beauty (which alone should be a capital offense in my view), comes loss of resolution. Loss of meaning. That's certainly something undesirable in a world that deals with precise information, no?

I'll not debate the loss of readability, it has been pointed out that that is subjective, but I will express my doubts that a blunt tool could ever do better on that front than a seasoned developer.

I *would* welcome a single commit that would be in effect recommended "client-side defaults" for our committers to apply voluntarily. I would also welcome a server-side script that makes CI *warn* if beautifying, erm, standardizing would produce a diff for the submitted PR. But that's it, warn, not fail, so whoever approves the merge makes their own decision: approve as-is or prompt for changes.

I think standardisation and beautification tools are beautiful: when they're used as that, just tools, they make our lives easier and simpler. But I also think when they're given say over sentient beings, it brings us one bit closer to the tyranny of the machine.

**Comment by runfalk** [comment] 2020-10-22 12:46
I'm pro black even though I don't like everything it does (I think [this double nesting](https://github.com/lektor/lektor/pull/823/files#diff-210e4b8a7b83429c65b6164c0e72d6612946ba9b9e09bc8dfad8ff7705301193R74-R82) is stupid, it particulary messes with parametrized unit tests in pytest). But that's just subjective so let's keep that outside of the discussion.

Black mostly messes up whitespace, but it does still (most of the time) respect where you choose to put empty lines. If you encode additional information or context through formatting the reader must be aware of your style. Unless they know or can infer exactly why your formatting is done in a certain way the extra resolution is meaningless. By removing this dimension as an opportunity to express oneself I'd even argue that we enforce more explicit ways of conveying the intention or structure of the code. When black destroys my formatting I'll usually end up rewriting it in a way that's easier to understand than previously.

The point of making it a tool is that we get strict enforcement and that things don't decay over time. If everything is voluntary we'll end up with slight variations and interpretations on how things should be formatted. We also have to spend time in each PR to think about formatting. I think your idea works great if there is a single maintainer but as soon as we have more people it no longer scales. I have previously tried to enforce style changes for diffs only and find that they generally cause more noise than what you gain.

Let the machine validate integrity and let us focus on the algorithmic problems instead :fist_raised:.

**Comment by runfalk** [comment] 2020-10-23 14:27
Closed because PR is merged.

**Closed as completed by runfalk** 2020-10-23 14:27 UTC
