### ISSUE TITLE
Checkboxes type not working in admin

### ISSUE THREAD

**Issue by magesavvy** [lektor/lektor#889] opened 2021-02-22 15:27 UTC
Trying to implement checkboxes type but unable to select in the admin.
Im just trying basic example

![checkboxes](https://user-images.githubusercontent.com/7961465/108729366-7246ad00-7550-11eb-817a-1c694778e599.png)

**Comment by dairiki** [comment] 2021-02-22 19:37
I've played with this a bit, and it happens for me too.  The issue seems to have appeared in Lektor 3.2.dev0 (and it affects 3.2 as well.)

For now, if running Lektor 3.1.3 is an option, that's a possible workaround.  It also appears to be fixed in current master.

**Comment by syx-pravin** [comment] 2021-09-15 12:38
It seems the issue is fixed in the current **master** branch.
**when can we expect the next release?**

**Comment by yagebu** [comment] 2021-09-18 09:32
This should be fixed in 3.2.1

**Closed as completed by yagebu** 2021-09-18 09:32 UTC
Labels: bug, admin-related
