### ISSUE TITLE
Win10 Python 3.6.2 run error.

### ISSUE THREAD

**Issue by andoresuperesu** [lektor/lektor#413] opened 2017-07-31 23:40 UTC
Currently getting the following error after just writing the command "lektor".

```
Traceback (most recent call last):
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\Scripts\lektor-script.py", line 11, in <module>
    load_entry_point('Lektor==3.0.1', 'console_scripts', 'lektor')()
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lektor-3.0.1-py3.6.egg\lektor\cli.py", line 8, in <module>
    from .i18n import get_default_lang, is_valid_language
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lektor-3.0.1-py3.6.egg\lektor\i18n.py", line 17, in <module>
    translations[_lang] = json.load(f)
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\Aperez\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 713: character maps to <undefined>
```

**Comment by goanpeca** [comment] 2017-07-31 23:57
This is a duplicate of https://github.com/lektor/lektor/issues/378 and is already fixed on master

**Comment by nixjdm** [comment] 2017-08-01 00:53
Agreed, it's a duplicate.

**Closed as completed by nixjdm** 2017-08-01 00:53 UTC
Labels: duplicate
