### ISSUE TITLE
Edit (pencil) button doesn't correctly link to Edit Admin page

### ISSUE THREAD

**Issue by mountainash** [lektor/lektor#815] opened 2020-10-08 09:17 UTC
Clicking the Edit (pencil) overlay button when viewing a (non root) alternative page on Lektor Server you are taken to a 'new page' entry for a new "bad" page name - not to edit the page as you'd expect.

### Steps to Reproduce
1. go to http://localhost:5000/de/internet/
1. click the pencil button in the top-right
1. Lektor Admin will load at http://localhost:5000/admin/root:internet%2Bde/edit with all inputs empty and a heading of "Edit “internet%2Bde”"

### Work arounds
- manually edit the URL in the browser replacing `%2B` with `+`
- use the sidebar in Admin to re-locate the page you want to edit
- revert to Lektor 3.1.3

I experience this with (and without) setting the `url` config in the `.lektorproject` file. Also with all three of the `url_style` config settings. I've tested on both Python 3.8 and 3.9. Lektor is running in Docker Compose with `lektor server -v -h 0.0.0.0`, but I don't think this would affect it.

**Comment by relikd** [comment] 2020-11-11 18:47
Can confirm this happens for me too. Did change nothing at my project, only updated to v3.2.0. Before clicking on the edit button the url shows correctly http://127.0.0.1:5000/admin/edit?path=%2Fde%2Finternet%2F, so I assume there is an issue when resolving the URL after clicking on the button.

Also, this might be an issue with our configuration since we both use alternates with the same format I assume. My project config is:
```
[alternatives.en]
name = English
primary = yes
url_prefix = /en/
locale = en_US

[alternatives.de]
name = German
url_prefix = /de/
locale = de_DE
```

**Comment by yagebu** [comment] 2020-11-14 15:43
I guess one of the underlying dependencies changed behaviour at some point, I can reproduce this and have a fix :)

**Closed as completed** 2020-11-14 15:59 UTC
Labels: bug, admin-related
