### ISSUE TITLE
Install script: can't open file virtualenv.py, no such file

### ISSUE THREAD

**Issue by rm-rf-etc** [lektor/lektor#619] opened 2018-11-05 01:00 UTC
## System Details

macOS Sierra 10.12.6
*using pyenv* to build python 2.7 (workaround for macOS issue with pre-TLS OpenSSL)
Python 2.7.15
OpenSSL 1.0.2p  14 Aug 2018

## Error Messages

```
$ curl -sf https://www.getlektor.com/install.sh | sh

Welcome to Lektor

This script will install Lektor on your computer.

   Lektor seems to be installed already.
   Continuing will delete:
   /usr/local/lib/lektor
   and remove this symlink:
   /usr/local/bin/lektor

Continue? [Yn] 

Installing at:
  bin: /usr/local/bin
  app: /usr/local/lib/lektor

Continue? [Yn] 
/Users/rob/.pyenv/versions/2.7.15/bin/python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 148, in <module>
  File "<stdin>", line 143, in main
  File "<stdin>", line 107, in install
  File "/Users/rob/.pyenv/versions/2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/rob/.pyenv/versions/2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## Interpretation

The expected file, `virtualenv.py`, is in the `src` directory, not the root directory, in the current tar file. The current tar file in my case seems to be:
https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz

## Proposed Solution:
Update installer logic near line 124 to also look for `virtualenv.py` in `./src`.
`Popen([sys.executable, './virtualenv.py', lib_dir], cwd=t).wait()`

For my system, `install.sh` worked after changing line 124 to this:
`Popen([sys.executable, './src/virtualenv.py', lib_dir], cwd=t).wait()`

**Comment by GrinDeg** [comment] 2018-11-05 04:49
Had the same problem on Linux Mint, Proposed solution worked for me

**Comment by Arstman** [comment] 2018-11-05 12:16
had the same problem on Ubuntu 16.04 too, and Proposed solution worked for me too.

**Comment by lfrancke** [comment] 2018-11-07 15:52
This commit is what broke this: https://github.com/pypa/virtualenv/commit/af5711ca9346b265f196a9cf266cecda9bca5b91#diff-51642b24ac9529f4baa0f483fa257d2d

First released in Virtualenv 16.1.0 on October 31 2018.

**Comment by ilessing** [comment] 2018-11-10 22:31
I had the same problem on MacOS 10.14 and proposed solution worked for me.

**Comment by airone506** [comment] 2018-11-21 19:22
I had the same problem on Ubuntu 18.04 and proposed solution worked for me too.

My big thanks to @rm-rf-etc for creating the issue, examining the problem & giving the working solution.

**Comment by lsrdg** [comment] 2018-11-28 09:20
Same issue on Archlinux and proposed solution worked. Thanks, @rm-rf-etc !

**Comment by filisko** [comment] 2018-12-04 14:33
Works here too in Ubuntu 18.04, thank you!

**Comment by nixjdm** [comment] 2018-12-04 18:56
Thank you all and especially for tracking down the root cause. This should now be fixed https://github.com/lektor/lektor-website/pull/261

**Closed as completed by nixjdm** 2018-12-04 18:56 UTC
Labels: installation

**Comment by clusin** [comment] 2020-03-23 04:53
Hi I'm seeing this issue as well, On macos catalina I'm seeing:
```
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 151, in <module>
  File "<stdin>", line 146, in main
  File "<stdin>", line 110, in install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by runfalk** [comment] 2020-03-23 08:42
Hi @clusin, I think your issue is the same as #740

**Comment by renateEta** [comment] 2020-03-27 14:20
Hello please I am new to linux.  I am facing this same error when trying to install lektor. I am confused if I am to edit the install.sh file or virtualenv.py file. Also can't seem to find any of the mentioned files in my machine to make changes. I am using Ubuntu 18.04.  Can someone help me please.

**Comment by runfalk** [comment] 2020-03-27 14:29
Hi @renateEta, this is probably because the installer is currently broken (see #720). You should be able to install it by downloading the suggested fixed script from https://raw.githubusercontent.com/lektor/lektor/5f2c070f6c89df5fbfb6cdf8c539207b925c59d8/bin/install.py and then run it using Python.

In a terminal you'd do:

```
curl -sf https://raw.githubusercontent.com/lektor/lektor/5f2c070f6c89df5fbfb6cdf8c539207b925c59d8/bin/install.py | python3
```

**Comment by renateEta** [comment] 2020-03-27 14:39
Thanks @runfalk . It works now.

**Comment by spsrinivas** [comment] 2020-04-22 09:08
Thanks, @runfalk

**Comment by LuisFalva** [comment] 2021-08-18 04:25
Your solution @runfalk worked for me, thank you!
