### ISSUE TITLE
Allow changing a page's model

### ISSUE THREAD

**Issue by tiberiuana** [lektor/lektor#98] opened 2016-01-13 17:18 UTC
It would be nice to support changing a page's model. This would allow migrating an existing page to a related template, while keeping its content.

Changing a page's model should keep all of its field content, even for fields not contained in the new model. This would allow easily rolling back to the initial state.

(Example: moving from _Page With Sidebar_ to _Page_ should not involve copy-pasting).

Further enhancement (for separate issue?):
The UI should warn if the page has unused fields, to prevent carrying forward invisible, uneditable content. It could also allow changing and removing them in a separate "unused fields" section.

**Comment by mitsuhiko** [comment] 2016-01-13 17:37
I assume this is for changing the model within the admin? You can already do it manually by changing the `contents.lr` file.

**Comment by tiberiuana** [comment] 2016-01-13 18:07
Indeed, I am referring to changing the model within the admin. This is something a content editor would do, without knowledge of (or access to) the .lr files.

**Comment by nixjdm** [comment] 2017-09-22 18:52
I'm marking this as on-hold pending the outcome of #457.

**Comment by nixjdm** [comment] 2018-05-23 17:58
Since we've had further discussion on #457 / #458, I'm removing the on-hold label. Though, it still may be prudent to handle #458 first, but I won't stop someone from picking this up.

Also from duplicate issue, [my quick thoughts on the matter (and why this is a little tricky)](https://github.com/lektor/lektor/issues/543#issuecomment-391143275):

> You can set a model during page creation, so why not change it after it's created?
> 
> Implementation issues, for one. Changing models will change all the other fields and saved content for the page. That could be fine, but it is definitely changing more than just **that field** - it'll change the whole admin page and all of that page's data. It should be prompted with a user verification probably, at least if other saved data will change, because it will generally all get deleted.
> 
> I'm fine with this, but it definitely has a UX element, unlike changing other existing field. There's something to be said for not having this as well. Perhaps having it, but allowing it to be disabled system-wide in the project file. It's maybe too powerful for a content generator, but might be loved by a dev.

**Comment by davidism** [comment] 2018-05-23 18:10
I'm not sure if the current plugin system can handle this, or if it would make more sense in core, but this seems similar to database migrations. A project adds / changes / removes a model, and creates a migration script describing how to go to / from the new version. The UI could perhaps show an interface for running migrations, but simply changing a model should not be possible as there would be too many issues caused by that.

The plugin would provide helpers to write these migrations. The plugin would see the migrations and could emit a message if the current state is not the latest one. Autogenerating a migration may be possible in some situations but should never be run without human review first. See Alembic, the SQLAlchemy migration tool, for a (very complex) example of this.

**Comment by nixjdm** [comment] 2018-05-23 19:22
Yes, this definitely is related to migrations. Right now, if you change a model for existing content, the change is mostly (always?) non-destructive, but may not make sense for the new model. I've done that before, and then had to manually fix the content files. For large numbers of effected content files that can be a big pain.

This *could* be added in to the admin with identical behavior as modifying models that have existing associated content right now, but that's probably be a bad idea. I would think it's presence in admin would encourage it's use, and without migrations, that's encouraging headaches, especially for the unwary.

**Comment by davidism** [comment] 2018-05-23 19:45
I'd avoid adding this to the UI. If you want to change the model, it will probably be a non-trivial translation that the UI can't do, at which point you'll be editing the `.lr` files and can edit the model there. If you have to migrate a large number of files, I'm pretty sure Lektor already exposes all the internals needed to write a script, although it's probably not documented enough.

**Comment by nixjdm** [comment] 2018-05-23 20:21
I agree, I don't think we should do this. I'll close this.

I'll make a separate ticket for thinking about how to handle migrations.

**Closed as completed by nixjdm** 2018-05-23 20:21 UTC
Labels: wontfix, design

**Comment by nixjdm** [comment] 2018-05-23 20:31
See #546
