### ISSUE TITLE
Getting "not configured for a valid publishing method" with sftp deployment target

### ISSUE THREAD

**Issue by sherbondy** [lektor/lektor#50] opened 2015-12-28 03:40 UTC
Hey there,

Was trying to have a go at doing a test deployment via sftp.
When I try through the admin gui, it fails silently with no feedback.
In fact, it says `Status: publishing done.`

I checked the server to see if the files were actually transferred, but no go.
So next I tried the cli:

```
lektor deploy production
```

And got this message:

```
Usage: lektor deploy [OPTIONS] [SERVER]

Error: Server "production" is not configured for a valid publishing method.
```

After some fiddling, I noticed that if I switched the url scheme to `ftp://` instead of `sftp://`, it _was_ recognized as a valid target for `lektor deploy`, but the actual deploy failed because the server is setup to only accept sftp connections.

Any ideas where I can go snooping around the code to look for a root cause?

Thanks.

**Comment by sherbondy** [comment] 2015-12-28 03:42
Further, if I use `sftp` in the url scheme, the `production` target is not recognized as the default (if I just do `lektor deploy`)

```
Error: Server "None" is not configured for a valid publishing method.
```

This makes me wonder if there is an odd issue with parsing the `.lektorproject` file that only springs up with `sftp` present for some reason.

**Comment by sherbondy** [comment] 2015-12-28 03:44
Here are the contents of my `.lektorproject` file (with the server name fuzzed, but this file also fails to have the sftp default target recognized):

```
[project]
name = The Project

[servers.production]
target = sftp://my_username@ssh.my.server.net/home/public/dev
name = Production
enabled = yes
default = yes
```

**Comment by mitsuhiko** [comment] 2015-12-28 09:16
For some reason I cannot reproduce this.  Any way you could verify that this still happens on 2.0.dev.0?

**Comment by mitsuhiko** [comment] 2016-01-09 09:39
I will close this most likely. I cannot reproduce it and there does not seem to be any activity on the issue otherwise.

**Comment by Almad** [comment] 2016-02-10 23:17
I can report this as well, with latest Lektor.

Changing protocol from `sftp` to `ftp` fixes it.

**Comment by mmaybeno** [comment] 2016-02-23 03:15
It's actually a typo I believe in the allowed publishers. Using 'ftps' instead of 'sftp' allows it to work. There is just some discrepancy with it and the doc pages.
https://github.com/lektor/lektor/blob/master/lektor/publisher.py#L617

**Comment by mmaybeno** [comment] 2016-02-24 16:29
Just wanted to update this for my own sanity. Looking into it more and becoming more familiar with the differences in `sftp` (SSH file transfer protocol) and `ftps` (file transfer protocol with TLS security). `publisher.py` is correct in using the right terminology in what it is providing. The docs also say that it is ftp with TLS, but the url protocol in the FTP example is mislabeled in saying it is `sftp`. This is where I think the confusion is coming from. Hopefully that will clarify things for anyone stumbling upon this.

**Comment by niijv** [comment] 2016-03-03 19:38
As pointed out by @mmaybeno the provided publisher is `ftps` and was mislabeled in the docs.
`sftp` will not be supported in the core but could be done by a plugin if needed.

**Closed as completed by niijv** 2016-03-03 19:38 UTC
